IkinciEl.UI/Controllers/AracListController.cs
using IkinciEl.CF.Models.Entities;
using IkinciEl.UI.Models.DAL;
using IkinciEl.UI.Models.VM;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace IkinciEl.UI.Controllers
{
    
    public class AracListController : Controller
    {
        // GET: AracList
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;


            if (TempData["aracList"] != null)
            {
                var aracList = TempData["aracList"] as List<AracVM>;
                ViewBag.Araclist = aracList;
            }
            else
            {
                List<AracVM> araclist = new AracDAL().AraclarinepsiniDoldur();
                ViewBag.Araclist = araclist;

            }


            

            List<ModelVM> modelList = new ModelDAL().ModelDoldur();
            ViewBag.Modellist = modelList;

            List<MarkaVM> markalist = new MarkaDAL().MarkaDoldur();
            ViewBag.Markalist = markalist;


            return View();
        }
        [HttpPost]
        public ActionResult Index(AracVM vm)
        {
            int markaID = Convert.ToInt32(Request["MarkaID"]);
            int modelID = Convert.ToInt32(Request["ModelID"]);


            List<AracVM> araclist = new AracDAL().AraclariDoldur(markaID, modelID);
            TempData["aracList"] = araclist;



            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult IndexAracOnay()
        {
            if (ModelState.IsValid)
            {
                KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
                ViewBag.kul = kullanici;

                bool onayDurumu = Convert.ToBoolean(Request["Onay"]);


                List<AracVM> aracList = new AracDAL().AracDoldur(onayDurumu);
                TempData["aracList"] = aracList;

                return RedirectToAction("Index");


            }
            else
            {
                ViewBag.loginError = "hata";
                return View("Index");
            }


        }


        [HttpPost]
        public ActionResult IndexAracDetay(int aracID)
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;


            AracDBVM arac = new AracDAL().AraciDoldur(aracID);
            TempData["araArac"] = arac;
            Session.Add("kaydet", 2);

            return RedirectToAction("AracEkle");
        }

        

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AracDetayTramer()
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;

            var araArac = TempData["araArac"] as AracDBVM;

            
            var tramerDurumBilgisi = new TramerDAL().TramerBilgisiDurumDoldur();

            ViewBag.TramerDurumlist= tramerDurumBilgisi;

            var parca = new ParcaDAL().ParcaDoldur();

            ViewBag.Parca = parca;


            return View(araArac);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AracDetayIlan()
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;

            var araArac = TempData["araArac"] as AracDBVM;

            var parca = new ParcaDAL().ParcaDoldur();

            ViewBag.Parca = parca;


            return View(araArac);
        }
        [HttpPost]
        public ActionResult AracDetayIlan(AracDBVM vM)
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;

            TempData["araArac"] = vM;
            

            return RedirectToAction("AracEkle");
        }
        [HttpPost]
        public ActionResult IndexAracEkle()
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;

            
            Session.Add("kaydet", 1);

            return RedirectToAction("AracEkle");
        }
        
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AracEkle()
        {
            var araArac = TempData["araArac"] as AracDBVM;

            var a = Session["kaydet"];

            ViewBag.Kaydet = a;
           


            

            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;

            List<ModelVM> modelList = new ModelDAL().ModelDoldur();
            ViewBag.Modellist = modelList;

            List<MarkaVM> markalist = new MarkaDAL().MarkaDoldur();
            ViewBag.Markalist = markalist;

            List<SirketVM> sirketlist = new SirketDAL().SirketDoldur();
            ViewBag.Sirketlist = sirketlist;

            List<StatuTipiVM> statuTipilist = new StatuTipiDAL().StatuTipiDoldur();
            ViewBag.StatuTipilist = statuTipilist;

            List<GovdeTipiVM> govdeTipilist = new GovdeTipiDAL().GovdeTipiDoldur();
            ViewBag.GovdeTipilist = govdeTipilist;

            List<YakitTipiVM> yakitTipilist = new YakitTipiDAL().YakitTipiDoldur();
            ViewBag.YakitTipilist = yakitTipilist;

            List<VitesTipiVM> vitesTipilist = new VitesTipiDAL().VitesTipiDoldur();
            ViewBag.VitesTipilist = vitesTipilist;

            List<RenkVM> renklist = new RenkDAL().RenkDoldur();
            ViewBag.Renklist = renklist;

            List<DonanimVM> donanimlist = new DonanimDAL().DonanimDoldur();
            ViewBag.Donanimlist = donanimlist;

            var parca = new ParcaDAL().ParcaDoldur();

            ViewBag.Parca = parca;
            



            if (araArac == null)
            {
                AracDBVM arac = new AracDBVM();

                List<TramerVM> tramerVMs = new List<TramerVM>();
                foreach (var parca2 in ViewBag.Parca)
                {
                    tramerVMs.Add(new TramerVM { ParcaID = parca2.ParcaID });
                }

                arac.tramerVMs= tramerVMs;

                return View(arac);
            }
            if (araArac.tramerVMs.Count <= 0)
            {
                List<TramerVM> tramerVMs = new List<TramerVM>();
                foreach (var parca2 in ViewBag.Parca)
                {
                    tramerVMs.Add(new TramerVM { ParcaID = parca2.ParcaID });
                }

                araArac.tramerVMs = tramerVMs;
            }

            return View(araArac);
        }

        [HttpPost]
        public ActionResult AracEkle(AracDBVM arac, string name)
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;

            var ilanSon = TempData["sonilan"] as Ilanbilgisi;
            TempData["araArac"] = arac;





            if (name== "Kaydet")
            {
                var a = new AracDAL().AracEkle(arac, kullanici.KullaniciID);
                TempData.Remove("araArac");
            }
            else if (name == "Guncelle")
            {
                var a = new AracDAL().AracGuncelle(arac);
                TempData.Remove("araArac");

            }
            else if (name == "Ilan Bilgisi")
            {
                return RedirectToAction("AracDetayIlan");
            }
            else if (name == "Tramer Bilgisi")
            {
                return RedirectToAction("AracDetayTramer");
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AracDetayTramer(AracDBVM vM)
        {
            KullaniciVM kullanici = Session["kullanici"] as KullaniciVM;
            ViewBag.kul = kullanici;

            TempData["araArac"] = vM;


            TempData["tramereBasldi"] = true;


            return RedirectToAction("AracEkle");
        }
    }
}

IkinciEl.UI/Views/AracList/AracDetayIlan.cshtml
@{
    ViewBag.Title = "AracDetayIlan";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";


}
@model IkinciEl.UI.Models.VM.AracDBVM
<h2>AracDetayIlan</h2>

@section ustMenu{

    @using (Html.BeginForm("AracDetayIlan", "AracList", FormMethod.Post))
    {
        
        for (int i = 0; i < Model.tramerVMs.Count; i++)
        {
           
            @Html.HiddenFor(a => a.tramerVMs[i].TramerID)
            @Html.HiddenFor(a => a.tramerVMs[i].ParcaID)
            <div class="col-md-4">
                @Html.HiddenFor(a => a.tramerVMs[i].TramerBilgisiDurumID)

            </div>
        }
        <div class="row" style="margin-top: 20px;">
            @Html.HiddenFor(a => a.IlanbilgisiID)


            <div class="col-md-4">
                <label for="inputEmail4" class="form-label">İlan Başlığı</label>
                @Html.TextBoxFor(a => a.IlanBaslıgi, new { @class = "form-control" })

            </div>
        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4" style="height: 200px; overflow: auto;">
                <label for="inputCity" class="form-label">İlan Detayı</label>
                @Html.TextBoxFor(a => a.IlanAckilma, new { @class = "form-control" })
            </div>


            @Html.HiddenFor(a => a.AracID)

            @Html.HiddenFor(a => a.KurumsalMİ)
            @Html.HiddenFor(a => a.SirketID)

            @Html.HiddenFor(a => a.StatuID)

            @Html.HiddenFor(a => a.AracFiyati)

            @Html.HiddenFor(a => a.Plaka)

            @Html.HiddenFor(a => a.AracMarkaID)

            @Html.HiddenFor(a => a.AracModelID)

            @Html.HiddenFor(a => a.GovdeTipiID)

            @Html.HiddenFor(a => a.YakıtTipiID)

            @Html.HiddenFor(a => a.VitesTipiId)

            @Html.HiddenFor(a => a.Kilometre)

            @Html.HiddenFor(a => a.RenkID)

            @Html.HiddenFor(a => a.DonanimID)



            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                <input type="submit" name="name" value="Kaydet" class="btn btn-primary" />
            </div>

        </div>


    }


}

@section altMenu{
}

IkinciEl.UI/Views/AracList/AracDetayTramer.cshtml
@{
    ViewBag.Title = "AracDetayTramer";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@model IkinciEl.UI.Models.VM.AracDBVM
<h2>AracDetayTramer</h2>

@section ustMenu{
    @using (Html.BeginForm("AracDetayTramer", "AracList", FormMethod.Post))
    {

        @Html.HiddenFor(a => a.IlanbilgisiID)
        @Html.HiddenFor(a => a.AracID)

        @Html.HiddenFor(a => a.KurumsalMİ)
        @Html.HiddenFor(a => a.SirketID)

        @Html.HiddenFor(a => a.StatuID)

        @Html.HiddenFor(a => a.AracFiyati)

        @Html.HiddenFor(a => a.Plaka)

        @Html.HiddenFor(a => a.AracMarkaID)

        @Html.HiddenFor(a => a.AracModelID)

        @Html.HiddenFor(a => a.GovdeTipiID)

        @Html.HiddenFor(a => a.YakıtTipiID)

        @Html.HiddenFor(a => a.VitesTipiId)

        @Html.HiddenFor(a => a.Kilometre)

        @Html.HiddenFor(a => a.RenkID)

        @Html.HiddenFor(a => a.DonanimID)
        @Html.HiddenFor(a => a.IlanbilgisiID)
        @Html.HiddenFor(a => a.IlanBaslıgi)
        @Html.HiddenFor(a => a.IlanAckilma)


        
        for (int i = 0; i < Model.tramerVMs.Count; i++)
        {
            @Html.HiddenFor(a => a.tramerVMs[i].TramerID)
            @Html.HiddenFor(a => a.tramerVMs[i].ParcaID)
            <div class="col-md-4">
                @ViewBag.Parca[i].ParcaAdi
                @Html.DropDownListFor(m => m.tramerVMs[i].TramerBilgisiDurumID, new SelectList(ViewBag.TramerDurumlist, "TramerBilgisiDurumID", "TramerBilgisiDurumAdi", Model.tramerVMs[i].TramerBilgisiDurumID), "Seçiniz", new { @class = "form-control" })
            </div>
        }



        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
            <input type="submit" name="name" value="Kaydet" class="btn btn-primary" />
        </div>



    }



}

@section altMenu{
}

IkinciEl.UI/Views/AracList/AracEkle.cshtml
@{
    ViewBag.Title = "AracEkle";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@model IkinciEl.UI.Models.VM.AracDBVM
<h2>AracEkle</h2>

@section ustMenu{

    @using (Html.BeginForm("AracEkle", "AracList", FormMethod.Post))
    {
        
        
        for (int i = 0; i < Model.tramerVMs.Count; i++)
        {
            @Html.HiddenFor(a => a.tramerVMs[i].ParcaID)
            @Html.HiddenFor(a => a.tramerVMs[i].TramerID)
            
            <div class="col-md-4">
                @Html.HiddenFor(a => a.tramerVMs[i].TramerBilgisiDurumID)

            </div>

        }

        <div class="row" style="margin-top: 20px;">
            @Html.HiddenFor(a => a.IlanbilgisiID)
            @Html.HiddenFor(a => a.IlanBaslıgi)
            @Html.HiddenFor(a => a.IlanAckilma)
            @Html.HiddenFor(a => a.AracID)

        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                BireyselMi/KurumsalMı:
                @Html.DropDownListFor(model => model.KurumsalMİ, new List<SelectListItem>()
                {
                    new SelectListItem() { Text = "Bireysel", Value = "False" },
                    new SelectListItem() { Text = "Kurumsal", Value = "True" }
                }, "Bireysel/Kurumsal", new { @class = "form-control" })

            </div>
            <div class="col-md-4">
                Sirket:
                @Html.DropDownListFor(model => model.SirketID, new SelectList(ViewBag.Sirketlist, "SirketID", "SirketAdi"), "Seçiniz", new { @class = "form-control" })

            </div>
            <div class="col-md-4">
                Araç Plakası:
                @Html.TextBoxFor(a => a.Plaka, new { @class = "form-control" })
            </div>
        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                Marka:
                @Html.DropDownListFor(model => model.AracMarkaID, new SelectList(ViewBag.Markalist, "AracMarkaID", "AracMarkaAdi"), " Seçiniz", new { @class = "form-control" })

            </div>
            <div class="col-md-4">
                Model:
                @Html.DropDownListFor(model => model.AracModelID, new SelectList(ViewBag.ModelList, "AracModelID", "AracModelAdi"), "Seçiniz", new { @class = "form-control" })
            </div>
            <div class="col-md-4">
                GovdeTipi:
                @Html.DropDownListFor(model => model.GovdeTipiID, new SelectList(ViewBag.GovdeTipilist, "GovdeTipiID", "GovdeTipiAdi"), "Seçiniz", new { @class = "form-control" })
            </div>
        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                YakitTipi:
                @Html.DropDownListFor(model => model.YakıtTipiID, new SelectList(ViewBag.YakitTipilist, "YakitTipiID", "YakitTipiAdi"), "Seçiniz", new { @class = "form-control" })

            </div>
            <div class="col-md-4">
                VitesTipi:
                @Html.DropDownListFor(model => model.VitesTipiId, new SelectList(ViewBag.VitesTipilist, "VitesTipiID", "VitesTipiAdi"), "Seçiniz", new { @class = "form-control" })

            </div>
            <div class="col-md-4">
                Araç Kilometresi:
                @Html.TextBoxFor(a => a.Kilometre, new { @class = "form-control" })
            </div>


        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                Renk:
                @Html.DropDownListFor(model => model.RenkID, new SelectList(ViewBag.Renklist, "RenkID", "RenkAdi"), "Seçiniz", new { @class = "form-control" })

            </div>
            <div class="col-md-4">
                Donanim:
                @Html.DropDownListFor(model => model.DonanimID, new SelectList(ViewBag.Donanimlist, "DonanimID", "DonanimAdi"), "Seçiniz", new { @class = "form-control" })
            </div>
            <div class="col-md-4">
                Araç Fiyatı:
                @Html.TextBoxFor(a => a.AracFiyati, new { @class = "form-control" })
            </div>


        </div>
        <div class="row" style="margin-top: 20px;">
            @if (ViewBag.Kaydet != 1)
            {
                <div class="col-md-4">
                    Onay Durumu:
                    @Html.DropDownListFor(model => model.OnayliMi, new SelectList(new List<SelectListItem> {
                        new SelectListItem { Text = "Onaylı", Value = true.ToString() },
                        new SelectListItem { Text = "Onaylı Değil", Value = false.ToString() }
                    }, "Value", "Text"), "Seçiniz", new { @class = "form-control" })
                </div>

            }


        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                @*@Html.ActionLink("Tramer", "AracDetayTramer", new { id = Model.IlanbilgisiID }, new { @class = "btn btn-primary" })*@
                <input type="submit" name="name" value="Tramer Bilgisi" class="btn btn-primary" />
            </div>
            <div class="col-md-4">
                @*@Html.ActionLink("Ilan Bilgisi", "AracDetayIlan", new { id = Model.IlanbilgisiID }, new { @class = "btn btn-primary" })*@
                <input type="submit" name="name" value="Ilan Bilgisi" class="btn btn-primary" />
            </div>


            @if (ViewBag.Kaydet == 1)
            {
                <div class="col-md-4 d-flex justify-content-end">
                    <input type="submit" name="name" value="Kaydet" class="btn btn-primary" />
                </div>
            }
            else
            {

                <div class="col-md-4 d-flex justify-content-end">
                    <input type="submit" name="name" value="Guncelle" class="btn btn-primary" />
                </div>
            }


        </div>





    }






}


@section altMenu{
}

IkinciEl.UI/Views/AracList/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Index</h2>

@section ustMenu{

    @using (Html.BeginForm("Index", "AracList", FormMethod.Post))
    {
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-6">
                @Html.DropDownList("MarkaID", new SelectList(ViewBag.Markalist, "AracMarkaID", "AracMarkaAdi"), "Marka Seçiniz", new { @class = "form-control" })
                @Html.DropDownList("ModelID", new SelectList(ViewBag.ModelList, "AracModelID", "AracModelAdi"), "Model Seçiniz", new { @class = "form-control" })
                <input type="submit" name="name" value="Seçimi bitir" class="btn btn-primary" />
            </div>

        </div>


    }
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6">
            @using (Html.BeginForm("IndexAracOnay", "AracList", FormMethod.Post))
            {
                @Html.DropDownList("Onay", new List<SelectListItem>()
                {
                    new SelectListItem() { Text = "Onaylı", Value = "true" },
                    new SelectListItem() { Text = "Onaysız", Value = "false" }
                }, "Onay Durumu..", new { @class = "form-control" })
                <input type="submit" name="name" value="Seçimi bitir" class="btn btn-primary" />
            }
        </div>
    </div>



    @using (Html.BeginForm("IndexAracEkle", "AracList", FormMethod.Post))
    {
        <div class="row" style="margin-top: 20px;">
            <div class="col-6">
                <input type="submit" name="name" value="Arac Ekle" class="btn btn-primary btn-lg btn-block" />
            </div>       
           
        </div>
            
     }
            <h1 class="mt-4">Araçlar</h1>


            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Araçlar
                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                            <tr>
                                <th>AracID</th>
                                <th>Araç Marka</th>
                                <th>Araç Model</th>
                                <th>Bireysel/Kurumsal</th>
                                <th>Kaydeden Kullanıcı</th>
                                <th>KAydetme Zamanı</th>
                            </tr>
                        </thead>
                        <tfoot>

                        </tfoot>
                        <tbody>


                            @using (Html.BeginForm("IndexAracDetay", "AracList", FormMethod.Post))
                            {

                                foreach (IkinciEl.UI.Models.VM.AracVM item in ViewBag.Araclist)
                                {

                                    <tr>
                                        <td>@item.AracID</td>
                                        <td>@item.AracMarka</td>
                                        <td>@item.AracModel</td>
                                        <td>@item.FirmaAdi</td>
                                        <td>@item.KaydedenKullanici</td>
                                        <td>@item.KaydetmeZamani</td>
                                        <td>
                                            <button type="submit" name="AracID" value="@item.AracID" class="btn btn-primary">Detay</button>
                                        </td>

                                    </tr>


                                }


                            }





                        </tbody>
                    </table>
                </div>
            </div>


            }


            @section altMenu{
            }